# version: "1.0"

services:
  # DATABASE Container
  kibet-database:
    image: mongo:3.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: kibet-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-database:/data/db
    env_file:
      - .env
    networks:
      - back-net

  # BACKEND Container
  kibet-backend:
    image: kibet/kibet-backend:v1.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        buildversion: v1.0.0

    # interactive mode like docker run -it
    stdin_open: true
    tty: true
    restart: always
    container_name: kibet-backend
    ports:
      - "5000:5000"
    networks:
      - back-net  
    
    env_file:
      - .env
    

  # FRONTEND Container
  kibet-client:
    image: kibet/kibet-client:v1.0.0
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        buildversion: v1.0.0

    # interactive mode like docker run -it
    stdin_open: true
    tty: true
    restart: always
    container_name: kibet-client
    ports:
      - "8080:80"
    env_file:

volumes:
  mongo-database:
    driver: local

networks:
  back-net:
    driver: bridge